trigger:
  branches:
    include:
    - main
  paths:
    include: 
    - src/productcatalogservice/.azure-pipelines/cicd.yml

pool: Linux

stages:
- template: ../../.azure-pipelines/templates/cicd.tpl.yml
  parameters:
    appName: productcatalogservice